auto_exposure:     True
exposure_auto_max: 0.06
exposure_auto_target: 35
exposure:          0.06
auto_gain:        True
gain_auto_max: 16
gain_auto_target: 35
gain:              4
auto_whitebalance: True
frame_id: /head_color_camera_r_link
stream_bytes_per_second: 124000000
auto_adjust_stream_bytes_per_second: False
trigger_mode: streaming
#packet_size: 9000
ip_address: 192.168.21.101
